version: '2'

volumes:
  bundle:

services:
  web:
    image: influitive/ruby:dev
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/src/app'
      - 'bundle:/bundle'
    working_dir: /usr/src/app
    environment:
      BUNDLE_PATH: /bundle
